### ISSUE TITLE
User-dependent out of range failure

### ISSUE THREAD

**Issue by taylortrimble** [mplewis/gwitter#1]
Super sweet repo! It was so good, that I put the GitHub repo gwitter on Twitter. And ate an apple fritter.

But sometimes I get this, and it appears to be user-dependent:

```
$ python gwitter.py dilipl
Traceback (most recent call last):
  File "gwitter.py", line 34, in <module>
    for event_bundle in public_events[0:(EVENT_BUNDLES_TO_READ-1)]:
  File "/Library/Python/2.7/site-packages/PyGithub-1.10.0-py2.7.egg/github/PaginatedList.py", line 62, in __iter__
    yield self.__list[index]
  File "/Library/Python/2.7/site-packages/PyGithub-1.10.0-py2.7.egg/github/PaginatedList.py", line 27, in __getitem__
    return self.__elements[index]
IndexError: list index out of range
```

Since "learning Python" isn't on the top of my list right now, I thought I'd pass it on to you. Good luck! Oh, also... Hi @dilipl!

**Comment by mplewis** [comment]
Nice find. I've had problems indexing, say, organizations, and users without any commits. I'm still not sure what happens when an empty commit message pops up. But this is the first user with valid commits in their public history that's caused the program problems.

This is a great time to start doing error catching too.

**Comment by dilipl** [comment]
Hey Taylor,
Nice to hear from you. Good catch
Not an expert at python either and I just saw this. Should download it and try it,
